wip

diff --git a/.github/actions/test_ya/action.yml b/.github/actions/test_ya/action.yml
--- a/.github/actions/test_ya/action.yml
+++ b/.github/actions/test_ya/action.yml
@@ -66,6 +66,7 @@ runs:
         echo "JUNIT_REPORT_PARTS=$TMP_DIR/junit-split" >> $GITHUB_ENV
         echo "TESTMO_TOKEN=${{ inputs.testman_token }}" >> $GITHUB_ENV
         echo "TESTMO_URL=${{ inputs.testman_url }}" >> $GITHUB_ENV
+        echo "TESTMO_STATUS=$(mktemp)"  >> $GITHUB_ENV
         echo "SUMMARY_LINKS=$(mktemp)" >> $GITHUB_ENV
         echo "GITHUB_TOKEN=${{ github.token }}" >> $GITHUB_ENV
         echo "BUILD_PRESET=${{ inputs.build_preset }}" >> $GITHUB_ENV
@@ -73,18 +74,9 @@ runs:
     - name: prepare
       shell: bash
       run: |
-        rm -rf $TMP_DIR $JUNIT_REPORT_XML $JUNIT_REPORT_PARTS $REPORTS_ARTIFACTS_DIR
-        mkdir -p $TMP_DIR $OUT_DIR $ARTIFACTS_DIR $TEST_ARTIFACTS_DIR $LOG_DIR $JUNIT_REPORT_PARTS $REPORTS_ARTIFACTS_DIR
+        rm -rf $TMP_DIR $REPORTS_ARTIFACTS_DIR
+        mkdir -p $TMP_DIR $OUT_DIR $ARTIFACTS_DIR $LOG_DIR $JUNIT_REPORT_PARTS $REPORTS_ARTIFACTS_DIR
     
-    - name: Install Node required for Testmo CLI
-      uses: actions/setup-node@v3
-      with:
-        node-version: 19
-    
-    - name: Install Testmo CLI
-      shell: bash
-      run: npm install -g @testmo/testmo-cli
-
     - name: Upload tests result to testmo
       id: th
       if: inputs.testman_token
@@ -136,15 +128,24 @@ runs:
             ;;
         esac
         
-        testmo automation:resources:add-link --name build --url "$RUN_URL" --resources testmo.json
-        testmo automation:resources:add-field --name git-sha --type string --value "${GITHUB_SHA:0:7}" --resources testmo.json
-        RUN_ID=$(
-        testmo automation:run:create --instance "$TESTMO_URL" --project-id ${{ inputs.testman_project_id }} \
-          --name "$TESTMO_RUN_NAME" --source "$TESTMO_SOURCE" --resources testmo.json \
-          --tags "$BRANCH_TAG" --tags "$EXTRA_TAG"
-        )
-        echo "runid=${RUN_ID}" >> $GITHUB_OUTPUT
-        echo "TEST_HISTORY_URL=${TESTMO_URL}/automation/runs/view/${RUN_ID}" >> $GITHUB_ENV
+#        testmo automation:resources:add-link --name build --url "$RUN_URL" --resources testmo.json
+#        testmo automation:resources:add-field --name git-sha --type string --value "${GITHUB_SHA:0:7}" --resources testmo.json
+#        RUN_ID=$(
+#        testmo automation:run:create --instance "$TESTMO_URL" --project-id ${{ inputs.testman_project_id }} \
+#          --name "$TESTMO_RUN_NAME" --source "$TESTMO_SOURCE" --resources testmo.json \
+#          --tags "$BRANCH_TAG" --tags "$EXTRA_TAG"
+#        )
+#        echo "runid=${RUN_ID}" >> $GITHUB_OUTPUT
+#        echo "TEST_HISTORY_URL=${TESTMO_URL}/automation/runs/view/${RUN_ID}" >> $GITHUB_ENV
+        
+        ydb/ci/gh-report/report.py testmo create-run --instance "$TESTMO_URL" --project "${{ inputs.testman_project_id }}" \
+          --name "$TESTMO_RUN_NAME" --source "$TESTMO_SOURCE" --tag "$BRANCH_TAG" --tag "$EXTRA_TAG" \
+          --run-link build "$RUN_URL" --run-field git-sha string "${GITHUB_SHA:0:7}" \
+          --run-field git-tree url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/tree/$GITHUB_SHA" \
+          --status "$TESTMO_STATUS"
+        
+        echo "TEST_HISTORY_URL=$(jq -r '.run_url' $TESTMO_STATUS)" >> $GITHUB_ENV
+        
 
     - name: Print test history link
       shell: bash
@@ -212,42 +213,28 @@ runs:
           params+=(--bazel-remote-base-uri "${{ inputs.bazel_remote_uri }}")
         fi
         
+        if [ ! -z "${{ inputs.bazel_remote_username }}" ]; then
+          params+=(
+            --bazel-remote-put
+            --bazel-remote-username "${{ inputs.bazel_remote_username }}"
+            --bazel-remote-password "${{ inputs.bazel_remote_password }}"
+          )
+        fi
+        
         echo "::debug::get version"
         ./ya --version
         
         echo "Tests are running..." | .github/scripts/tests/comment-pr.py
         
-        if [ ! -z "${{ inputs.bazel_remote_username }}" ]; then
-          echo "::debug::start tests"
+        echo "::debug::start tests"
 
-          ./ya test "${params[@]}" \
-            --bazel-remote-put --bazel-remote-username "${{ inputs.bazel_remote_username }}" --bazel-remote-password "${{ inputs.bazel_remote_password }}" -DCONSISTENT_DEBUG \
-            --log-file "$LOG_DIR/ya_log_prewarm.txt" --evlog-file "$LOG_DIR/ya_evlog_prewarm.jsonl" \
-            --dist-cache-evict-bins --cache-tests --no-dir-outputs --test-node-output-limit 1000000 --drop-graph-result-before-tests || (
-              RC=$?
-              echo "::debug::ya test RC=$RC"
-            )
-        fi
-        
-        echo "::debug::save tests reports"
-        ./ya test "${params[@]}" \
-          --stat --log-file "$LOG_DIR/ya_log.txt" --evlog-file "$LOG_DIR/ya_evlog.jsonl" -DCONSISTENT_DEBUG \
-          --cache-tests --dist-cache-evict-bins --no-dir-outputs --test-node-output-limit 1000000 --drop-graph-result-before-tests \
-          --junit "$JUNIT_REPORT_XML" --output "$OUT_DIR" || (
+        ./ya test "${params[@]}" -DCONSISTENT_DEBUG --jsonl-report "$LOG_DIR/test_report.jsonl" \
+          --dist-cache-evict-bins --cache-tests --no-dir-outputs \
+          --test-node-output-limit 1000000 --drop-graph-result-before-tests \
+          --output "$OUT_DIR" || (
             RC=$?
-            if [ $RC -ne 0 ]; then
-              echo "ya test returned $RC, check existence $JUNIT_REPORT_XML"
-              if [ -s "$JUNIT_REPORT_XML" ]; then
-                echo "$JUNIT_REPORT_XML exists"
-                ls -la "$JUNIT_REPORT_XML"
-              else
-                echo "$JUNIT_REPORT_XML doesn't exist or has zero size"
-                ls -la "$JUNIT_REPORT_XML" || true
-                exit $RC
-              fi
-            fi
-        )
-
+            echo "::debug::ya test RC=$RC"
+          )
     - name: archive unitest reports (orig)
       shell: bash
       run: |
@@ -272,36 +259,14 @@ runs:
       run: |
         tar -C $JUNIT_REPORT_PARTS/.. -czf $REPORTS_ARTIFACTS_DIR/junit_parts.xml.tar.gz $(basename $JUNIT_REPORT_PARTS)
 
-    - name: Unit test history upload results
+    - name: Upload test results
       if: inputs.testman_token
       shell: bash
       run: |
-        PROXY_ADDR=127.0.0.1:8888
-
-        openssl req -x509 -newkey rsa:2048 \
-          -keyout $TMP_DIR/key.pem -out $TMP_DIR/cert.pem \
-          -sha256 -days 1 -nodes -subj "/CN=127.0.0.1"
-        
-        ./ydb/ci/testmo-proxy/testmo-proxy.py -l $PROXY_ADDR \
-          --cert-file "$TMP_DIR/cert.pem" \
-          --cert-key "$TMP_DIR/key.pem" \
-          --target-timeout 3,10 \
-          --max-request-time 55 \
-          "$TESTMO_URL" &
-        
-        proxy_pid=$!
-        
-        NODE_TLS_REJECT_UNAUTHORIZED=0 testmo automation:run:submit-thread \
-          --instance "https://$PROXY_ADDR" --run-id "${{ steps.th.outputs.runid }}" \
-          --results "$JUNIT_REPORT_PARTS/*.xml"
-        
-        kill $proxy_pid
-
-    - name: Test history run complete
-      if: always() && inputs.testman_token
-      shell: bash
-      run: |
-        testmo automation:run:complete --instance "$TESTMO_URL" --run-id ${{ steps.th.outputs.runid }}
+        ydb/ci/gh-report/report.py testmo sink --status "$TESTMO_STATUS" --s3 \
+          --github-repo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" --github-sha "${GITHUB_SHA:0:7}" \
+          -m /.github/config/muted_ya.txt \
+          --basedir $OUT_DIR -i $LOG_DIR/test_report.jsonl
 
     - name: write tests summary
       shell: bash
@@ -310,22 +275,6 @@ runs:
         mkdir $ARTIFACTS_DIR/summary/
         
         cat $SUMMARY_LINKS | python3 -c 'import sys; print(" | ".join([v for _, v in sorted([l.strip().split(" ", 1) for l in sys.stdin], key=lambda a: (int(a[0]), a))]))' >> $GITHUB_STEP_SUMMARY
-        
-        .github/scripts/tests/generate-summary.py \
-          --summary-out-path $ARTIFACTS_DIR/summary/ \
-          --summary-url-prefix $S3_URL_PREFIX/summary/ \
-          --test-history-url $TEST_HISTORY_URL \
-          --build-preset "$BUILD_PRESET" \
-          "Tests" ya-test.html "$JUNIT_REPORT_XML"
-
-    - name: sync test results to s3
-      if: always()
-      shell: bash
-      run: |
-        echo "::group::s3-sync"
-        s3cmd sync -r --follow-symlinks --acl-public --no-progress --stats --no-check-md5 "$ARTIFACTS_DIR/" "$S3_BUCKET_PATH/"
-        s3cmd sync -r --follow-symlinks --acl-public --no-progress --stats --no-check-md5 "$TEST_ARTIFACTS_DIR/" "$S3_TEST_ARTIFACTS_BUCKET_PATH/"
-        echo "::endgroup::"
     
     - name: sync logs results to s3
       if: always()
@@ -335,10 +284,10 @@ runs:
         s3cmd sync --follow-symlinks --acl-private --no-progress --stats --no-check-md5 "$LOG_DIR/" "$S3_BUCKET_PATH/test_logs/"
         echo "::endgroup::"
         
-    - name: check test results
-      shell: bash
-      run: |
-        .github/scripts/tests/fail-checker.py "$JUNIT_REPORT_XML"
+#    - name: check test results
+#      shell: bash
+#      run: |
+#        .github/scripts/tests/fail-checker.py "$JUNIT_REPORT_XML"
 
     - name: show free space
       if: always()
