removeme

diff --git a/.github/actions/test/action.yml b/.github/actions/test/action.yml
--- a/.github/actions/test/action.yml
+++ b/.github/actions/test/action.yml
@@ -58,245 +58,259 @@ runs:
       echo "functestfilterfile=$(pwd)/.github/config/muted_functest.txt" >> $GITHUB_OUTPUT
       echo "pytest-logfilename=${{inputs.log_suffix}}-pytest-stdout.log" >> $GITHUB_OUTPUT
 
-  - name: configure s3cmd
-    shell: bash
-    run: |
-      cat <<EOF > $TMPDIR/s3cfg
-      [default]
-      access_key = ${aws_key_id}
-      secret_key = ${aws_secret_access_key}
-      bucket_location = ru-central1
-      host_base = storage.yandexcloud.net
-      host_bucket = %(bucket)s.storage.yandexcloud.net
-      EOF
-      echo "S3CMD_CONFIG=$TMPDIR/s3cfg" >> $GITHUB_ENV
-      echo "S3_BUCKET_PATH=s3://${{ inputs.aws_bucket }}/${{ github.repository }}/${{github.workflow}}/${{ github.run_id }}/${{inputs.log_suffix}}/" >> $GITHUB_ENV
-      echo "S3_URL_PREFIX=${{inputs.aws_endpoint}}/${{inputs.aws_bucket}}/${{ github.repository }}/${{github.workflow}}/${{github.run_id}}/${{inputs.log_suffix}}" >> $GITHUB_ENV
-    env:
-      aws_key_id: ${{inputs.AWS_KEY_ID }}
-      aws_secret_access_key: ${{inputs.AWS_KEY_VALUE}}
-
-  - name: Install Node required for Testmo CLI
-    uses: actions/setup-node@v3
-    with:
-      node-version: 19
-  - name: Install Testmo CLI
-    shell: bash
-    run: npm install -g @testmo/testmo-cli
-  - name: Test history run create
-    id: th
-    if: inputs.testman_token
-    shell: bash
-    env:
-      PR_NUMBER: ${{ github.event.number }}
-    run: |
-      RUN_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
-      BRANCH_TAG="$GITHUB_REF_NAME"
-      TESTMO_SOURCE="${{ inputs.log_suffix }}"
-      TESTMO_SOURCE="${TESTMO_SOURCE/_/-}"
-
-      case $GITHUB_EVENT_NAME in
-        workflow_dispatch)
-          TESTMO_RUN_NAME="${{ github.run_id }} manual"
-          EXTRA_TAG="manual"
-          ;;
-        pull_request | pull_request_target)
-          TESTMO_RUN_NAME="${{ github.run_id }} PR #${PR_NUMBER}"
-          EXTRA_TAG="pr"
-          BRANCH_TAG=""
-          ;;
-        schedule)
-          TESTMO_RUN_NAME="${{ github.run_id }} schedule"
-          EXTRA_TAG="schedule"
-          ;;
-        *)
-          TESTMO_RUN_NAME="${{ github.run_id }}"
-          EXTRA_TAG=""
-          ;;
-      esac
-
-      testmo automation:resources:add-link --name build --url $RUN_URL --resources testmo.json
-      testmo automation:resources:add-field --name git-sha --type string --value ${GITHUB_SHA:0:7} --resources testmo.json
-      testmo automation:run:create --instance "$TESTMO_URL" --project-id ${{inputs.testman_project_id}} --name "$TESTMO_RUN_NAME" \
-        --source "$TESTMO_SOURCE" --resources testmo.json \
-        --tags "$BRANCH_TAG" --tags "$EXTRA_TAG"  | \
-        echo "runid=$(cat)" >> $GITHUB_OUTPUT
-
-  - name: Print test history link
+#  - name: configure s3cmd
+#    shell: bash
+#    run: |
+#      cat <<EOF > $TMPDIR/s3cfg
+#      [default]
+#      access_key = ${aws_key_id}
+#      secret_key = ${aws_secret_access_key}
+#      bucket_location = ru-central1
+#      host_base = storage.yandexcloud.net
+#      host_bucket = %(bucket)s.storage.yandexcloud.net
+#      EOF
+#      echo "S3CMD_CONFIG=$TMPDIR/s3cfg" >> $GITHUB_ENV
+#      echo "S3_BUCKET_PATH=s3://${{ inputs.aws_bucket }}/${{ github.repository }}/${{github.workflow}}/${{ github.run_id }}/${{inputs.log_suffix}}/" >> $GITHUB_ENV
+#      echo "S3_URL_PREFIX=${{inputs.aws_endpoint}}/${{inputs.aws_bucket}}/${{ github.repository }}/${{github.workflow}}/${{github.run_id}}/${{inputs.log_suffix}}" >> $GITHUB_ENV
+#    env:
+#      aws_key_id: ${{inputs.AWS_KEY_ID }}
+#      aws_secret_access_key: ${{inputs.AWS_KEY_VALUE}}
+#
+#  - name: Install Node required for Testmo CLI
+#    uses: actions/setup-node@v3
+#    with:
+#      node-version: 19
+#  - name: Install Testmo CLI
+#    shell: bash
+#    run: npm install -g @testmo/testmo-cli
+#  - name: Test history run create
+#    id: th
+#    if: inputs.testman_token
+#    shell: bash
+#    env:
+#      PR_NUMBER: ${{ github.event.number }}
+#    run: |
+#      RUN_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
+#      BRANCH_TAG="$GITHUB_REF_NAME"
+#      TESTMO_SOURCE="${{ inputs.log_suffix }}"
+#      TESTMO_SOURCE="${TESTMO_SOURCE/_/-}"
+#
+#      case $GITHUB_EVENT_NAME in
+#        workflow_dispatch)
+#          TESTMO_RUN_NAME="${{ github.run_id }} manual"
+#          EXTRA_TAG="manual"
+#          ;;
+#        pull_request | pull_request_target)
+#          TESTMO_RUN_NAME="${{ github.run_id }} PR #${PR_NUMBER}"
+#          EXTRA_TAG="pr"
+#          BRANCH_TAG=""
+#          ;;
+#        schedule)
+#          TESTMO_RUN_NAME="${{ github.run_id }} schedule"
+#          EXTRA_TAG="schedule"
+#          ;;
+#        *)
+#          TESTMO_RUN_NAME="${{ github.run_id }}"
+#          EXTRA_TAG=""
+#          ;;
+#      esac
+#
+#      testmo automation:resources:add-link --name build --url $RUN_URL --resources testmo.json
+#      testmo automation:resources:add-field --name git-sha --type string --value ${GITHUB_SHA:0:7} --resources testmo.json
+#      testmo automation:run:create --instance "$TESTMO_URL" --project-id ${{inputs.testman_project_id}} --name "$TESTMO_RUN_NAME" \
+#        --source "$TESTMO_SOURCE" --resources testmo.json \
+#        --tags "$BRANCH_TAG" --tags "$EXTRA_TAG"  | \
+#        echo "runid=$(cat)" >> $GITHUB_OUTPUT
+#
+#  - name: Print test history link
+#    shell: bash
+#    run: |
+#      echo "10 [Test history](${TESTMO_URL}/automation/runs/view/${{steps.th.outputs.runid}})" >> $SUMMARY_LINKS
+#
+#  - name: Run unit tests
+#    id: ctest
+#    if: inputs.run_unit_tests == 'true'
+#    shell: bash
+#    run: |
+#      cd $WORKDIR/../build/ydb
+#
+#      echo "20 [Unittest log]($S3_URL_PREFIX/${{steps.init.outputs.logfilename}})" >> $SUMMARY_LINKS
+#
+#      # Sed removes coloring from the output
+#
+#      GTEST_OUTPUT="xml:$TESTREPDIR/unittests/" Y_UNITTEST_OUTPUT="xml:$TESTREPDIR/unittests/" \
+#        ctest -j28 --timeout 1200 --force-new-ctest-process --output-on-failure \
+#              --output-junit $TESTREPDIR/suites/ctest_report.xml \
+#              -L '${{inputs.test_label_regexp}}' -E "${CTEST_SKIP_SHARDS:-}" | \
+#        sed -u -e 's/\x1b\[[0-9;]*m//g' | \
+#        tee >(gzip --stdout > $ARTIFACTS_DIR/${{steps.init.outputs.logfilename}}) | \
+#        grep --line-buffered -E '(Test\s*#.*\*\*\*|\[FAIL\])|.*tests passed,.*tests failed out of' | \
+#        tee $WORKDIR/short.log || (
+#          RC=$?
+#          if [ $RC == 8 ]; then
+#            echo "ctest returned TEST_ERRORS, recovering.."
+#          else
+#            exit $RC
+#          fi
+#      )
+#
+#  - name: archive unitest reports (orig)
+#    if: inputs.run_unit_tests == 'true'
+#    shell: bash
+#    run: |
+#      tar -C $TESTREPDIR/ -czf $ARTIFACTS_DIR/xml_orig.tar.gz .
+#
+#  - name: postprocess xml reports
+#    if: inputs.run_unit_tests == 'true'
+#    shell: bash
+#    run: |
+#      echo "::group::extract-logs"
+#
+#      mkdir $ARTIFACTS_DIR/logs/
+#
+#      .github/scripts/tests/attach-logs.py \
+#        --url-prefix $S3_URL_PREFIX/logs/ \
+#        --ctest-report $TESTREPDIR/suites/ctest_report.xml \
+#        --junit-reports-path $TESTREPDIR/unittests/ \
+#        --decompress \
+#        $ARTIFACTS_DIR/${{steps.init.outputs.logfilename}} \
+#        $ARTIFACTS_DIR/logs/
+#
+#      echo "::endgroup::"
+#
+#      echo "::group::junit-postprocess"
+#
+#      .github/scripts/tests/junit-postprocess.py \
+#        --filter-file ${{steps.init.outputs.testfilterfile}} \
+#        $TESTREPDIR/unittests/
+#
+#      echo "::endgroup::"
+#
+#      echo "::group::ctest-postprocess"
+#
+#      .github/scripts/tests/ctest-postprocess.py \
+#        --filter-file ${{steps.init.outputs.testshardfilterfile}} \
+#        --decompress \
+#        $ARTIFACTS_DIR/${{steps.init.outputs.logfilename}} \
+#        $TESTREPDIR/suites/ctest_report.xml
+#
+#      tar -C $TESTREPDIR/ -czf $ARTIFACTS_DIR/reports.tar.gz .
+#
+#      echo "90 [XML reports archive]($S3_URL_PREFIX/reports.tar.gz)" >> $SUMMARY_LINKS
+#
+#      echo "::endgroup::"
+#
+#  - name: sync test results to s3
+#    if: always() && inputs.run_unit_tests == 'true'
+#    shell: bash
+#    run: |
+#      echo "::group::s3-sync"
+#      s3cmd sync -P --no-progress --stats --no-check-md5 -P $ARTIFACTS_DIR/ $S3_BUCKET_PATH
+#      echo "::endgroup::"
+#
+#  - name: Unit test history upload results
+#    if: always() && inputs.run_unit_tests == 'true' && inputs.testman_token
+#    shell: bash
+#    run: |
+#      testmo automation:run:submit-thread \
+#        --instance "$TESTMO_URL" --run-id ${{steps.th.outputs.runid}} \
+#        --results "$TESTREPDIR/unittests/*.xml"
+#      testmo automation:run:submit-thread \
+#        --exec-suppress \
+#        --instance "$TESTMO_URL" --run-id ${{steps.th.outputs.runid}} \
+#        --results "$TESTREPDIR/suites/*.xml" \
+#        -- cat $WORKDIR/short.log
+#
+#  - name: Run functional tests
+#    if: inputs.run_functional_tests == 'true' && (success() || failure())
+#    shell: bash
+#    run: |
+#      export source_root=$WORKDIR
+#      export build_root=$WORKDIR/../build/
+#
+#      echo "30 [Functional test log]($S3_URL_PREFIX/${{steps.init.outputs.pytest-logfilename}})" >> $SUMMARY_LINKS
+#      source $WORKDIR/ydb/tests/oss/launch/prepare.sh
+#
+#      rm -rf $ARTIFACTS_DIR/pytest/
+#      mkdir $ARTIFACTS_DIR/pytest/
+#
+#      cd $WORKDIR/ydb/tests/functional/
+#
+#      pytest \
+#        -p xdist -n 24 --dist worksteal \
+#        --timeout_method signal \
+#        -o junit_logging=log -o junit_log_passing_tests=False --junit-xml=$PYTESTREPDIR/pytest.xml \
+#        -ra --tb=no --show-capture=no \
+#        --github-repo $GITHUB_REPOSITORY --github-ref $GITHUB_SHA \
+#        --source-root $source_root \
+#        --build-root $build_root \
+#        --output-dir $TMPDIR/pytest/ \
+#        . | tee $ARTIFACTS_DIR/${{steps.init.outputs.pytest-logfilename}} || {
+#          RC=$?
+#          if [ $RC == 1 ]; then
+#            echo "pytest: tests were collected and run but some of the tests failed"
+#          else
+#            exit $RC
+#          fi;
+#        }
+#
+##        --artifacts-dir $ARTIFACTS_DIR/pytest/ \
+##        --artifacts-url $S3_URL_PREFIX/pytest/ \
+#
+#  - name: postprocess functional test reports
+#    if: always() && inputs.run_functional_tests == 'true'
+#    shell: bash
+#    run: |
+#      echo "::group::junit-postprocess"
+#
+#      # append orig pytest reports
+#      if [ -f "$ARTIFACTS_DIR/xml_orig.tar.gz" ]; then
+#        echo "add pytest to xml_orig.tar.gz"
+#        gzip -d $ARTIFACTS_DIR/xml_orig.tar.gz
+#        tar -C $TESTREPDIR/ -rvf $ARTIFACTS_DIR/xml_orig.tar pytest
+#        gzip -v $ARTIFACTS_DIR/xml_orig.tar
+#      fi
+#
+#      .github/scripts/tests/pytest-postprocess.py \
+#        --filter-file ${{ steps.init.outputs.functestfilterfile }} \
+#        $PYTESTREPDIR/
+#
+#      # make archive again with pytest reports
+#      tar -C $TESTREPDIR/ -czf $ARTIFACTS_DIR/reports.tar.gz .
+#      ls -la $ARTIFACTS_DIR/reports.tar.gz
+#
+#      echo "::endgroup::"
+#
+#
+#  - name: Functional tests history upload results
+#    if: always() && inputs.run_functional_tests == 'true' && inputs.testman_token
+#    shell: bash
+#    run: |
+#      testmo automation:run:submit-thread \
+#        --instance "$TESTMO_URL" --run-id ${{steps.th.outputs.runid}} \
+#        --results "$PYTESTREPDIR/*.xml" \
+#        -- cat $ARTIFACTS_DIR/${{steps.init.outputs.pytest-logfilename}}
+#
+#  - name: Test history run complete
+#    if: always() && inputs.testman_token
+#    shell: bash
+#    run: |
+#      testmo automation:run:complete --instance "$TESTMO_URL" --run-id ${{steps.th.outputs.runid}}
+#
+  
+  - name: get reports
+    if: always()
     shell: bash
     run: |
       echo "10 [Test history](${TESTMO_URL}/automation/runs/view/${{steps.th.outputs.runid}})" >> $SUMMARY_LINKS
-
-  - name: Run unit tests
-    id: ctest
-    if: inputs.run_unit_tests == 'true'
-    shell: bash
-    run: |
-      cd $WORKDIR/../build/ydb
-
-      echo "20 [Unittest log]($S3_URL_PREFIX/${{steps.init.outputs.logfilename}})" >> $SUMMARY_LINKS
-
-      # Sed removes coloring from the output
-      
-      GTEST_OUTPUT="xml:$TESTREPDIR/unittests/" Y_UNITTEST_OUTPUT="xml:$TESTREPDIR/unittests/" \
-        ctest -j28 --timeout 1200 --force-new-ctest-process --output-on-failure \
-              --output-junit $TESTREPDIR/suites/ctest_report.xml \
-              -L '${{inputs.test_label_regexp}}' -E "${CTEST_SKIP_SHARDS:-}" | \
-        sed -u -e 's/\x1b\[[0-9;]*m//g' | \
-        tee >(gzip --stdout > $ARTIFACTS_DIR/${{steps.init.outputs.logfilename}}) | \
-        grep --line-buffered -E '(Test\s*#.*\*\*\*|\[FAIL\])|.*tests passed,.*tests failed out of' | \
-        tee $WORKDIR/short.log || (
-          RC=$?
-          if [ $RC == 8 ]; then
-            echo "ctest returned TEST_ERRORS, recovering.."
-          else
-            exit $RC
-          fi
-      )
-
-  - name: archive unitest reports (orig)
-    if: inputs.run_unit_tests == 'true'
-    shell: bash
-    run: |
-      tar -C $TESTREPDIR/ -czf $ARTIFACTS_DIR/xml_orig.tar.gz .
-
-  - name: postprocess xml reports
-    if: inputs.run_unit_tests == 'true'
-    shell: bash
-    run: |
-      echo "::group::extract-logs"
-
-      mkdir $ARTIFACTS_DIR/logs/
-
-      .github/scripts/tests/attach-logs.py \
-        --url-prefix $S3_URL_PREFIX/logs/ \
-        --ctest-report $TESTREPDIR/suites/ctest_report.xml \
-        --junit-reports-path $TESTREPDIR/unittests/ \
-        --decompress \
-        $ARTIFACTS_DIR/${{steps.init.outputs.logfilename}} \
-        $ARTIFACTS_DIR/logs/
-
-      echo "::endgroup::"
-
-      echo "::group::junit-postprocess"
-      
-      .github/scripts/tests/junit-postprocess.py \
-        --filter-file ${{steps.init.outputs.testfilterfile}} \
-        $TESTREPDIR/unittests/
-
-      echo "::endgroup::"
-
-      echo "::group::ctest-postprocess"
-
-      .github/scripts/tests/ctest-postprocess.py \
-        --filter-file ${{steps.init.outputs.testshardfilterfile}} \
-        --decompress \
-        $ARTIFACTS_DIR/${{steps.init.outputs.logfilename}} \
-        $TESTREPDIR/suites/ctest_report.xml
-
-      tar -C $TESTREPDIR/ -czf $ARTIFACTS_DIR/reports.tar.gz .
-
       echo "90 [XML reports archive]($S3_URL_PREFIX/reports.tar.gz)" >> $SUMMARY_LINKS
-
-      echo "::endgroup::"
-
-  - name: sync test results to s3
-    if: always() && inputs.run_unit_tests == 'true'
-    shell: bash
-    run: |
-      echo "::group::s3-sync"
-      s3cmd sync -P --no-progress --stats --no-check-md5 -P $ARTIFACTS_DIR/ $S3_BUCKET_PATH
-      echo "::endgroup::"
-
-  - name: Unit test history upload results
-    if: always() && inputs.run_unit_tests == 'true' && inputs.testman_token
-    shell: bash
-    run: |
-      testmo automation:run:submit-thread \
-        --instance "$TESTMO_URL" --run-id ${{steps.th.outputs.runid}} \
-        --results "$TESTREPDIR/unittests/*.xml"
-      testmo automation:run:submit-thread \
-        --exec-suppress \
-        --instance "$TESTMO_URL" --run-id ${{steps.th.outputs.runid}} \
-        --results "$TESTREPDIR/suites/*.xml" \
-        -- cat $WORKDIR/short.log
-
-  - name: Run functional tests
-    if: inputs.run_functional_tests == 'true' && (success() || failure())
-    shell: bash
-    run: |
-      export source_root=$WORKDIR
-      export build_root=$WORKDIR/../build/
-
+      echo "20 [Unittest log]($S3_URL_PREFIX/${{steps.init.outputs.logfilename}})" >> $SUMMARY_LINKS
       echo "30 [Functional test log]($S3_URL_PREFIX/${{steps.init.outputs.pytest-logfilename}})" >> $SUMMARY_LINKS
-      source $WORKDIR/ydb/tests/oss/launch/prepare.sh
-      
-      rm -rf $ARTIFACTS_DIR/pytest/
-      mkdir $ARTIFACTS_DIR/pytest/
-      
-      cd $WORKDIR/ydb/tests/functional/
-      
-      pytest \
-        -p xdist -n 24 --dist worksteal \
-        --timeout_method signal \
-        -o junit_logging=log -o junit_log_passing_tests=False --junit-xml=$PYTESTREPDIR/pytest.xml \
-        -ra --tb=no --show-capture=no \
-        --github-repo $GITHUB_REPOSITORY --github-ref $GITHUB_SHA \
-        --source-root $source_root \
-        --build-root $build_root \
-        --output-dir $TMPDIR/pytest/ \
-        . | tee $ARTIFACTS_DIR/${{steps.init.outputs.pytest-logfilename}} || {
-          RC=$?
-          if [ $RC == 1 ]; then
-            echo "pytest: tests were collected and run but some of the tests failed"
-          else
-            exit $RC
-          fi;
-        }
 
-#        --artifacts-dir $ARTIFACTS_DIR/pytest/ \
-#        --artifacts-url $S3_URL_PREFIX/pytest/ \
-
-  - name: postprocess functional test reports
-    if: always() && inputs.run_functional_tests == 'true'
-    shell: bash
-    run: |
-      echo "::group::junit-postprocess"
+      cd $TESTREPDIR
+      curl -O https://storage.yandexcloud.net/ydb-tech-ci/ydb-platform/ydb/Nightly-run/6006816275/x86_64/reports.tar.gz
+      tar -xzf reports.tar.gz
   
-      # append orig pytest reports
-      if [ -f "$ARTIFACTS_DIR/xml_orig.tar.gz" ]; then
-        echo "add pytest to xml_orig.tar.gz"
-        gzip -d $ARTIFACTS_DIR/xml_orig.tar.gz
-        tar -C $TESTREPDIR/ -rvf $ARTIFACTS_DIR/xml_orig.tar pytest
-        gzip -v $ARTIFACTS_DIR/xml_orig.tar
-      fi
-      
-      .github/scripts/tests/pytest-postprocess.py \
-        --filter-file ${{ steps.init.outputs.functestfilterfile }} \
-        $PYTESTREPDIR/
-
-      # make archive again with pytest reports
-      tar -C $TESTREPDIR/ -czf $ARTIFACTS_DIR/reports.tar.gz .
-      ls -la $ARTIFACTS_DIR/reports.tar.gz
-
-      echo "::endgroup::"
-
-
-  - name: Functional tests history upload results
-    if: always() && inputs.run_functional_tests == 'true' && inputs.testman_token
-    shell: bash
-    run: |
-      testmo automation:run:submit-thread \
-        --instance "$TESTMO_URL" --run-id ${{steps.th.outputs.runid}} \
-        --results "$PYTESTREPDIR/*.xml" \
-        -- cat $ARTIFACTS_DIR/${{steps.init.outputs.pytest-logfilename}}
-
-  - name: Test history run complete
-    if: always() && inputs.testman_token
-    shell: bash
-    run: |
-      testmo automation:run:complete --instance "$TESTMO_URL" --run-id ${{steps.th.outputs.runid}}
-
   - name: write tests summary
     if: always()
     shell: bash
@@ -329,13 +343,13 @@ runs:
         });
 
 
-  - name: sync test results to s3
-    if: always()
-    shell: bash
-    run: |
-      echo "::group::s3-sync"
-      s3cmd sync -P --no-progress --stats --no-check-md5 -P $ARTIFACTS_DIR/ $S3_BUCKET_PATH
-      echo "::endgroup::"
+#  - name: sync test results to s3
+#    if: always()
+#    shell: bash
+#    run: |
+#      echo "::group::s3-sync"
+#      s3cmd sync -P --no-progress --stats --no-check-md5 -P $ARTIFACTS_DIR/ $S3_BUCKET_PATH
+#      echo "::endgroup::"
 
   - name: finish
     shell: bash
